spring.application.name=printcraft-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/printcraft_db
spring.datasource.username=postgres
spring.datasource.password=56789A

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

#  PUTTING IMPRTANT STUFFS__SECRATES
jwt.secret = 7m5wpp5gofd0VEBNrst1z0wpJa6JZBNVjS9BvJ7QqmY
jwt.expiration = 86400000


#  mail set_up --> Email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=samiran.roy.tech@gmail.com
spring.mail.password=rqxpvzaxafezrkdh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Razorpay
# Razorpay TEST keys
razorpay.key.id=rzp_test_T1FIq3Xnb1jIuA
razorpay.key.secret=Rs7xi3KbTn8kGH0paXX22k1n
razorpay.webhook.secret=Sami'sWebhook@Secret1$$$23
#file handling
# Accept up to 8MB (good quality originals)
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=25MB

# Then compress on backend to ~1-2MB before saving to S3
# Customer gets good print quality, you save 70% on AWS costs ?
#  sms API Key
fast2sms.api.key = yC8UVrpbM5GmovAXlxs3fiEHt70WYg6ezJcn4TwPONB9d2hS1jHuRfn36qSb8G9O4yF2li0TxKj1mWPE