spring.application.name=printcraft-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/printcraft_db
spring.datasource.username=postgres
spring.datasource.password=56789A

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

//PUTTING IMPRTANT STUFFS__SECRATES
jwt.secret = 7m5wpp5gofd0VEBNrst1z0wpJa6JZBNVjS9BvJ7QqmY
jwt.expiration = 86400000